# Generated by Django 5.2 on 2025-05-05 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logenvio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devocional',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devocionais', to='core.tema'),
        ),
        migrations.AddField(
            model_name='versiculo',
            name='devocional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiculos', to='core.devocional'),
        ),
    ]
